"""empty message

Revision ID: 02a9cc910ab4
Revises: 190163627111
Create Date: 2021-05-04 23:20:47.945686

"""

# revision identifiers, used by Alembic.
revision = '02a9cc910ab4'
down_revision = '190163627111'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
