"""empty message

Revision ID: 3820be62ef82
Revises: 02a9cc910ab4
Create Date: 2021-05-05 00:53:49.278715

"""

# revision identifiers, used by Alembic.
revision = '3820be62ef82'
down_revision = '02a9cc910ab4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
