"""empty message

Revision ID: 6339b0d57ee6
Revises: dc9bb32fa91d
Create Date: 2021-05-05 15:59:01.478487

"""

# revision identifiers, used by Alembic.
revision = '6339b0d57ee6'
down_revision = 'dc9bb32fa91d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
