"""empty message

Revision ID: dc9bb32fa91d
Revises: 3820be62ef82
Create Date: 2021-05-05 01:38:54.953408

"""

# revision identifiers, used by Alembic.
revision = 'dc9bb32fa91d'
down_revision = '3820be62ef82'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
